# Generated by Django 4.2.20 on 2025-06-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicom', '0002_request_display_text_alter_request_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='account',
            name='blocked',
            field=models.BooleanField(default=False, help_text='Whether this account is blocked from sending messages'),
        ),
        migrations.AddField(
            model_name='update',
            name='from_blocked_account',
            field=models.BooleanField(default=False, help_text='Whether this update came from a blocked account'),
        ),
    ]
