# Generated by Django 4.2.20 on 2025-05-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_bot',
        ),
        migrations.AddField(
            model_name='message',
            name='is_outgoing',
            field=models.BooleanField(default=None, help_text='True for outgoing messages, False for incoming, None for internal', null=True),
        ),
    ]
