# Generated by Django 4.2.20 on 2025-06-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='display_text',
            field=models.TextField(blank=True, help_text='Display version of the message text', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IDENTIFYING', 'Identifying'), ('CATEGORIZING', 'Categorizing'), ('CATEGORY_LIST_SENT', 'Category List Sent'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestcategory',
            name='processing_function',
            field=models.TextField(blank=True, help_text="Python function that determines if a request matches this category.\nMust be named 'process' and take a single 'request' argument.\nMust return True if the request matches, False otherwise.\nExample: def process(request) -> bool:\n    return 'help' in request.message.text.lower()", null=True),
        ),
    ]
