# Generated by Django 4.2.20 on 2025-05-28 16:34

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('unicom', '0002_rename_is_bot_to_is_outgoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='clicked_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='List of links that have been clicked', size=None),
        ),
        migrations.AddField(
            model_name='message',
            name='link_clicked',
            field=models.BooleanField(default=False, help_text='Whether any link in the email has been clicked'),
        ),
        migrations.AddField(
            model_name='message',
            name='opened',
            field=models.BooleanField(default=False, help_text='Whether the email has been opened'),
        ),
        migrations.AddField(
            model_name='message',
            name='time_link_clicked',
            field=models.DateTimeField(blank=True, help_text='When a link in the email was first clicked', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='time_opened',
            field=models.DateTimeField(blank=True, help_text='When the email was first opened', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tracking_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Unique ID for tracking email opens and clicks', null=True),
        ),
    ]
